<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Vgi.ExcelDna.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vgi.ExcelDna\Vgi.ExcelDna.csproj" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
